prgrms-be-devcourse/NBE5-6-2-Team06

- src/main/java/com/grepp/matnam/app/controller/api/user/UserApiController.java
- src/main/java/com/grepp/matnam/app/controller/api/user/payload/PreferenceRequest.java
- src/main/java/com/grepp/matnam/app/controller/web/user/UserController.java
- src/main/java/com/grepp/matnam/app/model/user/PreferenceService.java
- src/main/java/com/grepp/matnam/app/model/user/UserService.java
- src/main/resources/static/js/header.js
- src/main/resources/templates/index.html
- src/main/resources/templates/user/preference.html
- src/main/resources/templates/user/signin.html
- src/main/resources/templates/user/signup.html
사용자 취향 선택 기능을 구현했습니다.
- "feat: 회원가입 후 바로 로그인 처리하는 기능 구현": 사용자가 회원가입 즉시 로그인 처리되도록 기능 구현
- "feat: 사용자 취향 선택 기능 구현 및 화면 구현": 취향 선택은 최소 1개를 선택하도록 기능 구현
- "feat: 로그인 이후 마이페이지가 표시 되도록 화면 구현": 로그인 후 마이페이지 버튼이 나오도록 화면 구현
> feat: 사용자 취향 선택 기능 구현

- src/main/java/com/grepp/matnam/app/controller/api/user/UserApiController.java
- src/main/java/com/grepp/matnam/app/controller/web/user/UserController.java
- src/main/resources/templates/user/signup.html
회원가입 후 즉시 취향 설정 페이지로 전환되지 않는 문제를 해결했습니다.
- Token 저장 방식을 Cookie로 전환함에 따라 회원가입 로직을 수정
> fix: 회원가입 후 즉시 취향 설정 페이지로 전환되지 않는 문제 해결

- src/main/java/com/grepp/matnam/app/controller/api/mymap/MymapApiController.java
- src/main/java/com/grepp/matnam/app/controller/web/mymap/MymapController.java
- src/main/java/com/grepp/matnam/app/model/mymap/MymapRepository.java
- src/main/java/com/grepp/matnam/app/model/mymap/entity/Mymap.java
- src/main/java/com/grepp/matnam/app/model/mymap/entity/update-schema.sql
- src/main/resources/templates/map/add.html
mymap(개인 맛집 지도)를 마이페이지에서 등록할 수 있도록 했습니다.
- 마이페이지에서 /map/add로 이어지는 add.html 추가
- MymapEntity, MymapController, MymapApiController 추가
> feat: mymap 검색 및 신규 등록 기능 구현

- src/main/java/com/grepp/matnam/app/controller/api/team/TeamApiController.java
- src/main/java/com/grepp/matnam/app/controller/api/team/TeamReviewApiController.java
- src/main/java/com/grepp/matnam/app/controller/api/team/payload/ParticipantResponse.java
- src/main/java/com/grepp/matnam/app/controller/api/team/payload/ReviewRequest.java
- src/main/java/com/grepp/matnam/app/controller/api/team/payload/ReviewSummary.java
- src/main/java/com/grepp/matnam/app/controller/api/team/payload/TeamReviewResponse.java
- src/main/java/com/grepp/matnam/app/controller/web/team/TeamController.java
- src/main/java/com/grepp/matnam/app/controller/web/user/UserController.java
- src/main/java/com/grepp/matnam/app/model/team/ParticipantRepository.java
- src/main/java/com/grepp/matnam/app/model/team/TeamReviewRepository.java
- src/main/java/com/grepp/matnam/app/model/team/TeamReviewService.java
- src/main/java/com/grepp/matnam/app/model/team/TeamService.java
- src/main/java/com/grepp/matnam/app/model/team/entity/TeamReview.java
- src/main/java/com/grepp/matnam/app/model/user/UserService.java
- src/main/resources/templates/team/teamReview.html
모임을 진행하며 리뷰를 통해 매너온도가 증감되는 기능과 화면을 구현했습니다.
- 모임의 상태가 COMPLETE로 변경될 시 참가자의 매너온도 0.1 증가
- 모임 참가자 리뷰에 따른 매너온도 변화 기능
- 모임 리뷰 관련 화면 구현
- 로그인 검증 강화 (정지 상태 검증 추가)
> feat: 모임 리뷰 및 매너온도 기능 구현

- src/main/java/com/grepp/matnam/app/controller/api/team/TeamApiController.java
- src/main/java/com/grepp/matnam/app/controller/api/team/payload/TeamRequest.java
- src/main/java/com/grepp/matnam/app/controller/api/team/payload/TeamResponse.java
- src/main/java/com/grepp/matnam/app/controller/web/team/TeamController.java
- src/main/java/com/grepp/matnam/app/model/team/ParticipantRepository.java
- src/main/java/com/grepp/matnam/app/model/team/TeamRepository.java
- src/main/java/com/grepp/matnam/app/model/team/TeamService.java
- src/main/java/com/grepp/matnam/app/model/team/entity/Team.java
- src/main/resources/templates/team/teamCreate.html
- src/main/resources/templates/team/teamDetail.html
- src/main/resources/templates/team/teamPage.html
- src/main/resources/templates/team/teamSearch.html
- src/main/resources/templates/user/mypage.html
모임 신청하기
모임 찾기 페이지에 모임 정보 연결
모임과 회원 연결 - 충돌 해결
> fix : 모임과 회원 연결 - 충돌 해결

- src/main/java/com/grepp/matnam/app/controller/web/user/UserController.java
- src/main/resources/templates/user/mypage.html
마이페이지의 모임 리뷰 화면 기능을 구현했습니다.
- 완료된 모임의 모든 참가자에 대한 리뷰가 끝나지 않았다면 리뷰 작성 화면이 표시됨
- 작성할 리뷰가 없다면 해당 화면은 보이지 않음
> feat: 마이페이지 모임 리뷰 화면 기능 구현

- src/main/java/com/grepp/matnam/app/controller/api/team/TeamApiController.java
- src/main/java/com/grepp/matnam/app/controller/api/team/payload/TeamRequest.java
- src/main/java/com/grepp/matnam/app/controller/web/team/TeamController.java
- src/main/java/com/grepp/matnam/app/controller/web/user/UserController.java
- src/main/java/com/grepp/matnam/app/model/team/ParticipantRepository.java
- src/main/java/com/grepp/matnam/app/model/team/TeamRepository.java
- src/main/java/com/grepp/matnam/app/model/team/TeamService.java
- src/main/java/com/grepp/matnam/app/model/team/dto/TeamDto.java
- src/main/java/com/grepp/matnam/app/model/team/entity/Participant.java
- src/main/resources/templates/team/teamCreate.html
- src/main/resources/templates/team/teamDetail.html
- src/main/resources/templates/team/teamPage.html
- src/main/resources/templates/user/mypage.html
- src/main/resources/templates/user/test.html
모임 생성
마이페이지에서 참여 및 주최 모임 목록 조회
모임목록에 팀페이지 접속 추가
팀페이지에 참여자 및 주최자 상세 정보 조회
모임 중복 신청 방지
toDo :
모임 수정, 삭제 수정중
모임 참여자 신청 리스트 -> 모임 상세에 반영할 예정
> fix : 모임 생성 및 모임 조회

- src/main/java/com/grepp/matnam/app/controller/api/chat/ChatApiController.java
- src/main/java/com/grepp/matnam/app/controller/api/team/payload/TeamRequest.java
- src/main/java/com/grepp/matnam/app/controller/web/chat/ChatController.java
- src/main/java/com/grepp/matnam/app/controller/web/team/TeamController.java
- src/main/java/com/grepp/matnam/app/model/chat/ChatService.java
- src/main/java/com/grepp/matnam/app/model/chat/dto/MessageDto.java
- src/main/java/com/grepp/matnam/app/model/chat/entity/Chat.java
- src/main/java/com/grepp/matnam/app/model/chat/entity/ChatRoom.java
- src/main/java/com/grepp/matnam/app/model/chat/repository/ChatRepository.java
- src/main/java/com/grepp/matnam/app/model/chat/repository/ChatRepositoryCustom.java
- src/main/java/com/grepp/matnam/app/model/chat/repository/ChatRepositoryCustomImpl.java
- src/main/java/com/grepp/matnam/app/model/chat/repository/ChatRoomRepository.java
- src/main/java/com/grepp/matnam/app/model/team/TeamService.java
- src/main/java/com/grepp/matnam/app/model/team/entity/Participant.java
- src/main/java/com/grepp/matnam/app/model/team/entity/Team.java
- src/main/java/com/grepp/matnam/infra/config/WebSocketConfig.java
- src/main/resources/data.sql
- src/main/resources/templates/team/teamDetail.html
- src/main/resources/templates/team/teamEdit.html
- src/main/resources/templates/team/teamPage.html
- src/main/resources/templates/team/teamSearch.html
> feat: 채팅 기능 연결

- pom.xml
- src/main/java/com/grepp/matnam/app/controller/web/user/OAuth2UserController.java
- src/main/java/com/grepp/matnam/app/model/user/CustomOauth2UserService.java
- src/main/java/com/grepp/matnam/app/model/user/UserService.java
- src/main/java/com/grepp/matnam/app/model/user/dto/CustomOAuth2User.java
- src/main/java/com/grepp/matnam/app/model/user/dto/GoogleResponse.java
- src/main/java/com/grepp/matnam/app/model/user/dto/OAuth2Response.java
- src/main/java/com/grepp/matnam/app/model/user/dto/UserDto.java
- src/main/java/com/grepp/matnam/infra/config/PasswordEncoderConfig.java
- src/main/java/com/grepp/matnam/infra/config/SecurityConfig.java
- src/main/java/com/grepp/matnam/infra/oauth2/OAuth2AuthenticationSuccessHandler.java
- src/main/resources/templates/user/oauth2-signup.html
- src/main/resources/templates/user/signin.html
- src/main/resources/templates/user/signup.html
OAuth - 구글 로그인/회원가입 기능을 구현했습니다.
- 소셜 계정으로 로그인 하는 경우 부가적인 사용자 정보 입력을 받도록 함 (닉네임, 주소, 나이, 성별)
- 소셜 계정으로 회원가입을 한 계정의 경우 초기 비밀번호가 세팅됨
- 구글 로그인/회원가입 기능 구현
> feat: OAuth - 구글 로그인/회원가입 기능 구현

- src/main/java/com/grepp/matnam/app/controller/web/chat/ChatController.java
- src/main/java/com/grepp/matnam/app/model/chat/ChatService.java
- src/main/java/com/grepp/matnam/app/model/chat/dto/MessageDto.java
- src/main/resources/templates/team/teamDetail.html
- src/main/resources/templates/team/teamPage.html
모임 게시글 신고 화면과 채팅 신고 기능 및 화면을 구현했습니다.
- 팀페이지에 채팅 신고 기능 구현
- 모임 게시글 신고 버튼 구현
> feat: 신고 기능 구현 및 화면 구현

- src/main/java/com/grepp/matnam/app/controller/api/user/UserApiController.java
- src/main/java/com/grepp/matnam/app/controller/web/user/UserController.java
- src/main/java/com/grepp/matnam/app/model/team/TeamService.java
- src/main/java/com/grepp/matnam/app/model/user/UserService.java
- src/main/java/com/grepp/matnam/infra/auth/AuthenticationUtils.java
- src/main/java/com/grepp/matnam/infra/auth/CookieUtils.java
- src/main/java/com/grepp/matnam/infra/auth/PasswordValidator.java
- src/main/java/com/grepp/matnam/infra/error/GlobalExceptionHandler.java
- src/main/java/com/grepp/matnam/infra/response/Messages.java
- src/main/resources/templates/user/mypage.html
- src/main/resources/templates/user/signin.html
- src/main/resources/templates/user/signup.html
User 관련 컴포넌트의 코드 품질과 유지보수성을 개선하기 위해 백엔드와 프론트엔드 코드 모두 리팩토링을 진행했습니다.
- 의존성 주입 방식을 필드 주입에서 생성자 주입으로 통일
- 공통 유틸리티 클래스 추가
- AuthenticationUtils: 인증 관련 공통 기능
- CookieUtils: 쿠키 처리 공통 기능
- PasswordValidator: 비밀번호 유효성 검증
- 중복 코드 제거 및 책임 분리
- 컨트롤러에서 비즈니스 로직 제거
- 반복되는 인증 확인 및 쿠키 처리 코드 추출
- 예외 처리 일원화
- GlobalExceptionHandler 도입
- 컨트롤러에서 try-catch 블록 제거
- 에러 메시지 상수화
- Messages 클래스로 에러 메시지 통합 관리
- 로깅 개선
- 민감 정보 로그 제외
- 의미 있는 로그 메시지 작성
- signup.html, signin.html 수정
- 백엔드에서 쿠키 설정하도록 변경하여 프론트엔드 쿠키 설정 코드 제거
- 비밀번호 정책 안내 및 클라이언트 측 검증 추가
- 에러 처리 개선 및 일관성 있는 메시지 처리
- 로깅 기능 강화
- 코드 중복 제거
- 가독성 향상
- 유지보수성 개선
- 백엔드
- infra/auth/AuthenticationUtils.java (신규)
- infra/auth/CookieUtils.java (신규)
- infra/auth/PasswordValidator.java (신규)
- infra/response/Messages.java (신규)
- infra/error/GlobalExceptionHandler.java …
> refactor: User 컴포넌트 리팩토링

- src/main/java/com/grepp/matnam/app/controller/api/admin/payload/TeamResponse.java
- src/main/java/com/grepp/matnam/app/controller/api/team/TeamApiController.java
- src/main/java/com/grepp/matnam/app/controller/api/team/payload/TeamRequest.java
- src/main/java/com/grepp/matnam/app/controller/api/team/payload/TeamUpdateRequest.java
- src/main/java/com/grepp/matnam/app/controller/api/team/payload/UpdatedTeamRequest.java
- src/main/java/com/grepp/matnam/app/controller/web/team/TeamController.java
- src/main/java/com/grepp/matnam/app/model/team/TeamRepository.java
- src/main/java/com/grepp/matnam/app/model/team/TeamService.java
- src/main/java/com/grepp/matnam/app/model/team/dto/TeamDto.java
- src/main/java/com/grepp/matnam/app/model/team/entity/Team.java
- src/main/resources/templates/team/teamCreate.html
- src/main/resources/templates/team/teamDetail.html
- src/main/resources/templates/team/teamEdit.html
- src/main/resources/templates/team/teamPage.html
- src/main/resources/templates/team/teamReview.html
- src/main/resources/templates/user/mypage.html
승인 거절
모임 수정
승인되기 전 팀 페이지에 안 올라오게 하기
> feat: 승인 거절 및 모임 수정 기능 구현

- src/main/java/com/grepp/matnam/app/controller/api/mymap/MymapApiController.java
- src/main/java/com/grepp/matnam/app/controller/web/mymap/MymapController.java
- src/main/java/com/grepp/matnam/app/controller/web/user/UserController.java
- src/main/java/com/grepp/matnam/app/model/mymap/MymapRepository.java
- src/main/resources/templates/map/add.html
- src/main/resources/templates/map/editMap.html
- src/main/resources/templates/user/mypage.html
마이페이지 내 공개/비공개 장소 수 표시 기능을 추가했습니다.
-  place Count model 속성 주입
- 메서드 경로 분리(/pinned), POST/PATCH/DELETE 통일
- deletePlace -> updateActivatedStatus(추후 soft delete 활성화 예정)
- updatePlace -> updatePinnedStatus
- saveMyPlace -> savePlace로 네이밍 통일
- 공개/ 비공개 장소 수 UI 개선
- 버튼 이벤트 함수명 일관화
- fetch URL 및 메서드 경로 정리
- CSS 일부 수정
> feat: 마이페이지 내 맛집 저장 수 표시 기능 추가

- src/main/java/com/grepp/matnam/app/model/mymap/MymapService.java
MymapService 클래스 생성 및 로직을 분리했습니다. 
- MymapService 클래스 생성 및 비즈니스 로직 분리
> feat: MymapService 클래스 생성 및 비즈니스 로직 분리

- src/main/java/com/grepp/matnam/app/controller/api/notification/NotificationApiController.java
- src/main/java/com/grepp/matnam/app/controller/api/sse/SseApiController.java
기존의 SseController의 위치와 이름이 이상해서 수정했습니다.
* SseController -> SseApiController 클래스명 변경
* 패키지 경로 controller/sse -> controller/api/sse 로 이동
* NotificationApiController 매핑 형식 통일
> refactor: 알림 기능 리팩터링

- src/main/resources/templates/user/mypage.html
> fix: 모임 주최 중일때도 모임 수정 접근 불가

- src/main/java/com/grepp/matnam/infra/config/SecurityConfig.java
- src/main/resources/templates/team/teamPage.html
관리자가 채팅방에 접근 못하는 부분 권한 설정
채팅창 ui 수정했습니다
권한 설정
채팅 수정
> fix: 권한 설정 및 채팅 수정

- src/main/resources/templates/index.html
메인 페이지 UI 수정
- section 간격 조정
- 임시 이미지 추가 및 멘트 수정
> refactor: 메인 페이지 내 ui 수정

- src/main/java/com/grepp/matnam/app/controller/api/admin/AdminTeamApiController.java
- src/main/java/com/grepp/matnam/app/model/restaurant/RestaurantRepository.java
- src/main/java/com/grepp/matnam/app/model/restaurant/RestaurantService.java
- src/main/java/com/grepp/matnam/app/model/team/TeamRepository.java
- src/main/java/com/grepp/matnam/app/model/team/TeamService.java
- src/main/java/com/grepp/matnam/app/model/user/UserService.java
- src/main/resources/static/css/admin-styles.css
- src/main/resources/static/js/statistics.js
- src/main/resources/templates/admin/notification.html
- src/main/resources/templates/admin/statistics.html
- src/main/resources/templates/map/add.html
- src/main/resources/templates/map/teamMap.html
- src/main/resources/templates/team/teamCreate.html
- src/main/resources/templates/team/teamDetail.html
- src/main/resources/templates/team/teamEdit.html
- src/main/resources/templates/team/teamPage.html
- src/main/resources/templates/team/teamReview.html
- src/main/resources/templates/team/teamSearch.html
- src/main/resources/templates/user/mypage.html
- src/main/resources/templates/user/passwordChange.html
- src/main/resources/templates/user/signin.html
관리자 기능 및 UI 개선했고, 사용자 페이지 UI 수정했습니다.
* 관리자
* 대시보드
*  UI 반응형으로 수정
* 통계 및 분석 
* 날짜 내림차 순으로 나오는 현상 수정
* 차트 데이터 수정 (activated=true 인 데이터만 조회하도록 쿼리 수정. 단,  사용자 통계는 제외 (탈퇴 회원에 대한 통계 포함))
* UI 반응형으로 수정
* 알림 관리
* 공지사항 목록 탭 분리
* 사용자
* 리뷰 작성 알림 순서 수정
* UI 수정
* 마이페이지 모임 수정 버튼 수정
* 모임 찾기 검색창 수정
* 모임 상세 페이지 수정
* 모임 모집 중인 상태일 때만 참가 신청하기 버튼 보이게
* 참가자에게만 보이는 팀 페이지 이동하는 버튼 추가
* 모임 상태, 참여하기 섹션으로 위치 이동 
* common-toast.js 누락된 페이지들에 추가
* teamPage.html 파일 내의 showToast 함수와 이름이 중복되서 이름 변경
* teamPage.html : showToast -> showToastTeamPage
> feat: 관리자 기능 및 UI 개선

- src/main/resources/templates/user/signin.html
fix: 관리자 로그인 시 관리자 페이지로 이동 
쿠키 저장 항목 변경에 따른 오류 수정
> fix: 관리자 로그인 시 관리자 페이지로 이동

- src/main/java/com/grepp/matnam/app/controller/api/team/TeamApiController.java
- src/main/java/com/grepp/matnam/app/controller/api/team/payload/TeamRequest.java
- src/main/java/com/grepp/matnam/app/controller/web/team/TeamController.java
- src/main/java/com/grepp/matnam/app/controller/web/user/UserController.java
- src/main/java/com/grepp/matnam/app/model/team/ParticipantRepository.java
- src/main/java/com/grepp/matnam/app/model/team/TeamRepository.java
- src/main/java/com/grepp/matnam/app/model/team/TeamService.java
- src/main/java/com/grepp/matnam/app/model/team/entity/Team.java
- src/main/resources/templates/team/teamCreate.html
- src/main/resources/templates/user/mypage.html
- 마이페이지에 모임 페이지네이션 구현
- 모임 생성 시 최대인원 수정(2명 이상)
- 스웨거 operation 추가
> feat: 페이지네이션 구현, 모임 생성 최대인원 수정

- src/main/java/com/grepp/matnam/app/controller/api/mymap/MymapApiController.java
- src/main/java/com/grepp/matnam/app/controller/api/mymap/MymapTeamApiController.java
- src/main/resources/static/js/auth.js
- src/main/resources/templates/team/teamDetail.html
- src/main/resources/templates/team/teamEdit.html
- src/main/resources/templates/team/teamPage.html
- src/main/resources/templates/user/mypage.html
기존 모임 수정 페이지에 있던 삭제 버튼을 팀페이지 및 마이페이지로 이전했습니다. 
- auth 가 중복 선언되어 Uncaught SyntaxError: Identifier 'auth' has already been declared (at auth.js:1:1) 오류가 뜨는 것을 확인했습니다. 직접적인 영향은 없으나 전역 오염 방지를 위해 일부 코드를 수정했습니다.
- teamEdit 페이지 내 기존 모임삭제 버튼을 삭제했습니다.
- 마이페이지 및 팀페이지에 모임 삭제 버튼을 추가했습니다. 
- Mymap 관련 Api 명세서에 넣을 설명을 추가했습니다. 
- 모임 상세 페이지 내 일부 버튼의 hover 효과를 추가했습니다.
> refactor: 모임 삭제 기능 추가

- src/main/java/com/grepp/matnam/app/controller/api/sse/SseApiController.java
- src/main/java/com/grepp/matnam/app/model/sse/SseRepository.java
- src/main/java/com/grepp/matnam/app/model/sse/SseService.java
> chore: 불필요한 코드 삭제

- src/main/java/com/grepp/matnam/app/controller/api/restaurant/RestaurantApiController.java
- src/main/java/com/grepp/matnam/app/model/restaurant/RestaurantAiService.java
- src/main/java/com/grepp/matnam/infra/llm/comfig/RecommendationConfig.java
- src/test/java/com/grepp/matnam/app/restaurants/RecommendationTest.java
객체로 값을 전달 시(dto 등) langchain4j가 인식 못하는 오류가 있을 수도 있어서 애초에 keywords를 받아서
문자열 형식으로 전달하는 방향으로 수정하였습니다
결과 : 이제 키워드를 기준으로 완벽하게 출력 확인했습니다
fix: UserMessage 수정
fix: llm 시스템 전달 메시지 String 형태로 수정
> fix: 시스템 전달 메시지 String 형태로 수정

- src/main/resources/templates/team/teamDetail.html
- src/main/resources/templates/team/teamPage.html
> refactor: 일부 ui 수정
